AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GenerateEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 30
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: 'arn:aws:bedrock:*::foundation-model/amazon.nova-lite-v1:0'
      Events:
        GenerateEmailApi:
          Type: Api
          Properties:
            Path: /generate_email
            Method: post

Outputs:
  GenerateEmailApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate_email/"
